[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "Fixes buggy jetpack fall damage logic."
websiteUrl = "https://github.com/Hamunii/JetpackFallFix"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-HookGenPatcher = "0.0.5"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/JetpackFallFix.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]